version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/CatsDB
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 5823
#    depends_on:
#      - db
#    networks:
#      - app-network


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cats2-kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    depends_on:
      - zookeeper


  cat-bd:
    image: postgres:latest
    container_name: "cats_bd"
    volumes:
      - postgres_data:/var/lib/postgresql/catsdata
    environment:
      POSTGRES_DB: Cats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5823
    ports:
      - "5432:5432"

  cat-service:
    build:
      context: ./Cats/
      dockerfile: Dockerfile
    depends_on:
      - cat-bd
      - kafka
    ports:
      - "8080-8080"
    networks:
      - kafka-network


  owner-bd:
    image: postgres:latest
    container_name: "owners_bd"
    volumes:
      - postgres_data:/var/lib/postgresql/ownersdata
    environment:
      POSTGRES_DB: Owners
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5823
    ports:
      - "5433:5432"

  owner-service:
    build:
      context: ./Owners/
      dockerfile: Dockerfile

    depends_on:
      - owner-bd
      - kafka
    ports:
      - "8081-8081"
    networks:
      - kafka-network


  user-bd:
    image: postgres:latest
    container_name: "users_bd"
    volumes:
      - postgres_data:/var/lib/postgresql/usersdata
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5823
    ports:
      - "5434:5432"
    networks:
      - kafka-network

  user-service:
    container_name: "user_service"
    build:
      context: ./GateWay/
      dockerfile: Dockerfile
    depends_on:
      - user-bd
      - kafka
    ports:
      - "8082-8082"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  postgres_data: