CREATE TABLE IF NOT EXISTS owners
(
    name character(255) COLLATE "default",
    date date,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    CONSTRAINT owners_pkey PRIMARY KEY (id)
    );

